### ISSUE TITLE
Unable to build from git in Arch Linux

### ISSUE THREAD

**Issue by ngoonee** [royshil/obs-backgroundremoval#172]
Trying to build current master, and getting errors on building 0rt. The end of the error is here, full log attached.

[385/976] Building CXX object CMakeFiles/onnxruntime_session.dir/home/ngoonee/.cache/aurutils/sync/obs-backgroundremoval-git/src/obs-backgroundremoval/build/Ort-prefix/src/Ort/onnxruntime/core/session/inference_session.cc.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/ngoonee/.cache/aurutils/sync/obs-backgroundremoval-git/src/obs-backgroundremoval/build/Ort-prefix/src/Ort/tools/ci_build/build.py", line 2812, in <module>
    sys.exit(main())
  File "/home/ngoonee/.cache/aurutils/sync/obs-backgroundremoval-git/src/obs-backgroundremoval/build/Ort-prefix/src/Ort/tools/ci_build/build.py", line 2727, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/home/ngoonee/.cache/aurutils/sync/obs-backgroundremoval-git/src/obs-backgroundremoval/build/Ort-prefix/src/Ort/tools/ci_build/build.py", line 1349, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/ngoonee/.cache/aurutils/sync/obs-backgroundremoval-git/src/obs-backgroundremoval/build/Ort-prefix/src/Ort/tools/ci_build/build.py", line 740, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/ngoonee/.cache/aurutils/sync/obs-backgroundremoval-git/src/obs-backgroundremoval/build/Ort-prefix/src/Ort/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '/home/ngoonee/.cache/aurutils/sync/obs-backgroundremoval-git/src/obs-backgroundremoval/build/Ort-prefix/src/Ort-build/Release', '--config', 'Release', '--', '-j16']' returned non-zero exit status 1.
make[2]: *** [CMakeFiles/Ort.dir/build.make:89: Ort-prefix/src/Ort-stamp/Ort-build] Error 1
make[1]: *** [CMakeFiles/Makefile2:114: CMakeFiles/Ort.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
[errors.txt](https://github.com/royshil/obs-backgroundremoval/files/10952878/errors.txt)

**Comment by umireon** [comment]
This is the upstream issue
https://github.com/microsoft/onnxruntime/issues/14923

**Comment by GenocideStomper** [comment]
I see https://github.com/royshil/obs-backgroundremoval/commit/4c2e152adc73c769c8cde2bb0db4c5995b41e664 was merged yesterday. 

However @ngoonee I can't get your obs-backgroundremoval-git to work from the AUR. It's asking which file to patch. Do you maybe have to update your script to reflect yesterday's commit?

**Comment by ngoonee** [comment]
> I see [4c2e152](https://github.com/royshil/obs-backgroundremoval/commit/4c2e152adc73c769c8cde2bb0db4c5995b41e664) was merged yesterday.
> 
> However @ngoonee I can't get your obs-backgroundremoval-git to work from the AUR. It's asking which file to patch. Do you maybe have to update your script to reflect yesterday's commit?

Yes I do need to update it, (basically the patch should not longer be needed), but it doesn't build on my system even with those changes so I haven't updated the PKGBUILD to AUR yet.

**Comment by umireon** [comment]
This build problem should be fixed by #250
